apiVersion: v2
name: ingress-nginx
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 4.1.0
appVersion: 1.2.0
home: https://github.com/kubernetes/ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
  - ingress
  - nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
type: application
maintainers:
  - name: rikatz
  - name: strongjz
  - name: tao12345666333
engine: gotpl
kubeVersion: ">=1.19.0-0"
annotations:
  # Use this annotation to indicate that this chart version is a pre-release.
  # https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/prerelease: "false"
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=changelog
  artifacthub.io/changes: |
    - "[8481](https://github.com/kubernetes/ingress-nginx/pull/8481) Fix log creation in chroot script"
    - "[8479](https://github.com/kubernetes/ingress-nginx/pull/8479) changed nginx base img tag to img built with alpine3.14.6"
    - "[8478](https://github.com/kubernetes/ingress-nginx/pull/8478) update base images and protobuf gomod"
    - "[8468](https://github.com/kubernetes/ingress-nginx/pull/8468) Fallback to ngx.var.scheme for redirectScheme with use-forward-headers when X-Forwarded-Proto is empty"
    - "[8456](https://github.com/kubernetes/ingress-nginx/pull/8456) Implement object deep inspector"
    - "[8455](https://github.com/kubernetes/ingress-nginx/pull/8455) Update dependencies"
    - "[8454](https://github.com/kubernetes/ingress-nginx/pull/8454) Update index.md"
    - "[8447](https://github.com/kubernetes/ingress-nginx/pull/8447) typo fixing"
    - "[8446](https://github.com/kubernetes/ingress-nginx/pull/8446) Fix suggested annotation-value-word-blocklist"
    - "[8444](https://github.com/kubernetes/ingress-nginx/pull/8444) replace deprecated topology key in example with current one"
    - "[8443](https://github.com/kubernetes/ingress-nginx/pull/8443) Add dependency review enforcement"
    - "[8434](https://github.com/kubernetes/ingress-nginx/pull/8434) added new auth-tls-match-cn annotation"
    - "[8426](https://github.com/kubernetes/ingress-nginx/pull/8426) Bump github.com/prometheus/common from 0.32.1 to 0.33.0"
